apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca-issuer
  namespace: sample-sandbox
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-sandbox-ca
  namespace: sample-sandbox
spec:
  secretName: sample-sandbox-ca-tls
  commonName: sample-sandbox.svc.cluster.local
  isCA: true
  issuerRef:
    name: selfsigned-ca-issuer
